/**
 * This file was auto-generated by the Titanium Module SDK helper for Android
 * Appcelerator Titanium Mobile
 * Copyright (c) 2009-2017 by Appcelerator, Inc. All Rights Reserved.
 * Licensed under the terms of the Apache Public License
 * Please see the LICENSE included with this distribution for details.
 *
 */
package de.appwerft.midimanager;

import java.util.ArrayList;

import org.appcelerator.kroll.KrollDict;
import org.appcelerator.kroll.KrollProxy;
import org.appcelerator.kroll.annotations.Kroll;

import android.media.midi.MidiDeviceInfo;
import android.media.midi.MidiDeviceInfo.PortInfo;

@Kroll.proxy(creatableInModule = MidimanagerModule.class)
public class MidiDeviceInfoProxy extends KrollProxy {

	private static final String LCAT = "ExampleProxy";

	public MidiDeviceInfo deviceinfo;

	public MidiDeviceInfoProxy() {
		super();
	}

	public MidiDeviceInfoProxy(MidiDeviceInfo deviceinfo) {
		super();
		this.deviceinfo = deviceinfo;
	}

	@Kroll.getProperty
	@Kroll.method
	public int getMessage() {
		return deviceinfo.getId();
	}

	@Kroll.getProperty
	@Kroll.method
	public int getType() {
		return deviceinfo.getType();
	}

	@Kroll.method
	public KrollDict getProperties() {
		KrollDict res = new KrollDict();
		res.put("manufacturer", deviceinfo.getProperties().getString(MidiDeviceInfo.PROPERTY_MANUFACTURER));
		res.put("product", deviceinfo.getProperties().getString(MidiDeviceInfo.PROPERTY_PRODUCT));
		res.put("name", deviceinfo.getProperties().getString(MidiDeviceInfo.PROPERTY_NAME));
		res.put("version", deviceinfo.getProperties().getString(MidiDeviceInfo.PROPERTY_VERSION));
		res.put("btdevice", deviceinfo.getProperties().getString(MidiDeviceInfo.PROPERTY_BLUETOOTH_DEVICE));
		return res;
	}

	@Kroll.getProperty
	@Kroll.method
	public Object[] getPorts() {
		ArrayList<PortProxy> portList = new ArrayList<PortProxy>();
		for (PortInfo port : deviceinfo.getPorts()) {
			portList.add(new PortProxy(port));
		}
		return portList.toArray();
	}

}
