/**
 * This file was auto-generated by the Titanium Module SDK helper for Android
 * Appcelerator Titanium Mobile
 * Copyright (c) 2009-2018 by Appcelerator, Inc. All Rights Reserved.
 * Licensed under the terms of the Apache Public License
 * Please see the LICENSE included with this distribution for details.
 *
 */
package de.appwerft.midimanager;

import java.util.ArrayList;
import java.util.HashMap;

import org.appcelerator.kroll.KrollModule;
import org.appcelerator.kroll.annotations.Kroll;

import org.appcelerator.titanium.TiApplication;

import android.content.Context;
import android.content.pm.PackageManager;
import android.media.midi.MidiDeviceInfo;
import android.media.midi.MidiManager;

import org.appcelerator.kroll.common.Log;
import org.appcelerator.kroll.common.TiConfig;

@Kroll.module(name = "Midimanager", id = "de.appwerft.midimanager")
public class MidimanagerModule extends KrollModule {

	// Standard Debugging variables
	private static final String LCAT = "MidimanagerModule";
	private static final boolean DBG = TiConfig.LOGD;
	private static Context ctx;
	private static MidiManager mm;

	// You can define constants with @Kroll.constant, for example:
	// @Kroll.constant public static final String EXTERNAL_NAME = value;

	public MidimanagerModule() {
		super();
	}

	@Kroll.onAppCreate
	public static void onAppCreate(TiApplication app) {
		Log.d(LCAT, "inside onAppCreate");
		ctx = app.getApplicationContext();
		mm = (MidiManager) ctx.getSystemService(Context.MIDI_SERVICE);

		// put module init code that needs to run when the application is created
	}

	// Methods
	@Kroll.method
	public boolean hasSystemFeature() {
		return ctx.getPackageManager().hasSystemFeature(PackageManager.FEATURE_MIDI);

	}

	@Kroll.method
	public Object[] getDevices() {
		ArrayList<DeviceProxy> deviceList = new ArrayList<DeviceProxy>();
		MidiDeviceInfo[] infos = mm.getDevices();
	    for (MidiDeviceInfo info : infos) {
	    	deviceList.add(new DeviceProxy(info));
	    }
	    return deviceList.toArray();
	}

	@Kroll.method
	@Kroll.setProperty
	public void setExampleProp(String value) {
		Log.d(LCAT, "set example property: " + value);
	}

}
