/**
 * This file was auto-generated by the Titanium Module SDK helper for Android
 * Appcelerator Titanium Mobile
 * Copyright (c) 2009-2017 by Appcelerator, Inc. All Rights Reserved.
 * Licensed under the terms of the Apache Public License
 * Please see the LICENSE included with this distribution for details.
 *
 */
package de.appwerft.midimanager;

import org.appcelerator.kroll.KrollDict;
import org.appcelerator.kroll.KrollProxy;
import org.appcelerator.kroll.annotations.Kroll;
import org.appcelerator.titanium.TiC;
import org.appcelerator.kroll.common.Log;
import org.appcelerator.kroll.common.TiConfig;
import org.appcelerator.titanium.util.TiConvert;
import org.appcelerator.titanium.proxy.TiViewProxy;
import org.appcelerator.titanium.view.TiCompositeLayout;
import org.appcelerator.titanium.view.TiCompositeLayout.LayoutArrangement;
import org.appcelerator.titanium.view.TiUIView;

import android.app.Activity;
import android.media.midi.MidiDeviceInfo.PortInfo;
import android.media.midi.MidiInputPort;


@Kroll.proxy(creatableInModule = MidimanagerModule.class)
public class MidiInputPortProxy extends KrollProxy {
	private static final String LCAT = "ExampleProxy";

	public MidiInputPort port;

	
	public  MidiInputPortProxy() {
		super();
	}

	
	public  MidiInputPortProxy(MidiInputPort port) {
		super();
		this.port = port;
	}
}
